services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001" # 9000 for S3 API, 9001 for MinIO Console
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  minio-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minio-api
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin1234
      - MINIO_SECURE=false
    depends_on:
      - minio
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  minio_data:
