services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001" # 9000 for S3 API, 9001 for MinIO Console
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  minio-api:
    build:
      context: ./minio
      dockerfile: Dockerfile
    container_name: minio-api
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin1234
      - MINIO_SECURE=false
    depends_on:
      - minio
    networks:
      - app_network

  flow:
    build: ./backend/flow
    depends_on:
      pg:
        condition: service_healthy
    ports:
      - "8001:8000"
    env_file:
      - ./backend/flow/.env
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
    networks:
      - app_network
  pg:
    image: postgres:latest

    environment:
      POSTGRES_USER: admin
      PGUSER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin","-d", "database"]
      interval: 10s
      timeout: 5s
      retries: 5
    # volumes:
    #   - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  minio_data:
